variable "filename" {
	default = "/home/ubuntu/DevOps/Terraform/Terraform_list/devops_automated.txt"
}

variable "content" {
	default = "This is autogenerated from a variable"
}

variable "content_map" {
type = map
default = {
"content1" = "This is a cool content 1"
"content2" = "This is a cooler content 2"
}
}

variable "file_list" {
type = list
default = ["/home/ubuntu/DevOps/Terraform/Terraform_list/file_1.txt","/home/ubuntu/DevOps/Terraform/Terraform_list/file_2.txt"]
}
