steps:

# Validate the message in _ACTION variable
- name: "alpine/k8s:1.25.15"
  entrypoint: 'bash'
  args:
  - -c
  - |
    apk add --no-cache jq
    echo "${_ACTION}"
    echo "${_ACTION}" | jq . || echo "Invalid JSON structure in _ACTION"

# Extract deployment name, namespace, and other details from the Pub/Sub message
- name: "alpine/k8s:1.25.15"
  entrypoint: 'bash'
  args:
  - -c
  - |
    apk add --no-cache jq
    echo "$_ACTION" > /workspace/action.json
    deployment_name=$(jq -r '.labels."k8s-pod/app"' /workspace/action.json)
    namespace=$(jq -r '.resource.labels.namespace_name' /workspace/action.json)
    project_id=$(jq -r '.resource.labels.project_id' /workspace/action.json)
    location=$(jq -r '.resource.labels.location' /workspace/action.json)
    cluster_name=$(jq -r '.resource.labels.cluster_name' /workspace/action.json)
    if [ -z "$deployment_name" ] || [ -z "$namespace" ]; then
      echo "Error: Deployment name or namespace is missing."
      exit 1
    fi
    echo $project_id > /workspace/project_id.txt
    echo $location > /workspace/location.txt
    echo $cluster_name > /workspace/cluster_name.txt
    echo $deployment_name > /workspace/deployment_name.txt
    echo $namespace > /workspace/namespace.txt
