variable "filename" {
	default = "/home/ubuntu/DevOps/Terraform/Terraform_Map/devops_automated.txt"
}

variable "content" {
	default = "This is autogenerated from a variable"
}

variable "content_map" {
type = map
default = {
"content1" = "This is a cool content 1"
"content2" = "This is a coller comtent 2"
}
}

